Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using ThuvienMvc.Services.Interfaces;
using ThuvienMvc.Dtos.AuthorDto;
using ThuvienMvc.Models.Authentications;
using ThuvienMvc.Models;
using X.PagedList;

namespace LibraryMVC.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorService _context;
        public AuthorController(IAuthorService context)
        {
            _context = context;
        }

        [AuthenAdmin]
        public ActionResult Index(string name, int page = 1)
        {
            page = page < 1 ? 1 : page;
            int pageSize = 7;


            IPagedList<Author> authors = _context.GetPagedAuthor(name, page, pageSize);
            if (!string.IsNullOrEmpty(name) && (authors == null || !authors.Any()))
            {
                ViewBag.Message = "Không tồn tại tác giả nào theo kết quả tìm kiếm.<a href='javascript:history.back()'>Quay lại</a>";
            }
            ViewData["SearchName"] = name;
            return View(authors);
        }

        [AuthenAdmin]
        public ActionResult Create()
        {
            var model = new CreateAuthorDto(); 
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateAuthorDto model)
        {
            if (ModelState.IsValid)
            {

                _context.Create(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [AuthenAdmin]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var author = _context.GetById(id);
            if (author == null)
            {
                return NotFound();
            }

            _context.Delete(id);
            return RedirectToAction("Index");
        }


        [AuthenAdmin]
        public ActionResult Edit(int id)
        {
            var result = _context.GetById(id);
            if (result == null)
            {
                return NotFound();
            }

            return View(result);
        }


        [AuthenAdmin]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AuthorDto author)
        {
            if (ModelState.IsValid)
            {
                _context.Update(author);
                return RedirectToAction("Index");
            }
            return View(author);
        }

    }
}

Controllers/BookController.cs
using ThuvienMvc.Dtos.BookDtos;
using ThuvienMvc.Services.Implements;
using ThuvienMvc.Services.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using ThuvienMvc.Models;
using X.PagedList;
using ThuvienMvc.Dtos.AuthorDto;
using ThuvienMvc.Models.Authentications;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace ThuvienMvc.Controllers
{
    public class BookController : Controller
    {
        // GET: BookController
        private readonly IBookService _context;
        private readonly IAuthorService _authorService;
        private readonly IGenreservice _genreService;
        private readonly Data _data;
        public BookController(IBookService context , IAuthorService authorService,  IGenreservice genreService , Data data)
        {
            _data = data;
            _context = context;
            _authorService = authorService;
            _genreService = genreService;   
        }
        //[HttpGet]
        /*public ActionResult Index()
        {
            var book = _context.GetAll();
            return View(book);
        }
        */

        public ActionResult Index(string name , int page = 1)
        {
            page = page < 1 ? 1 : page;
            int pageSize = 7;
 

            IPagedList<Book> books = _context.GetPagedBooks(name,page, pageSize);
            if (!string.IsNullOrEmpty(name) && (books == null || !books.Any()))
            {
                ViewBag.Message = "Không tồn tại sách nào theo kết quả tìm kiếm .<a href='javascript:history.back()'>Quay lại</a>";
            }
            ViewData["SearchName"] = name;
            return View(books); 
        }
        //public ActionResult Page(int page = 1)
        //{
        //    page = page < 1 ? 1 : page;
        //    int pagesize = 7;
        //    IPagedList<Book> books = _context.GetPagedBooks(page, pagesize);

        //    return View(books);
        //}

        //[HttpGet]
        //public ActionResult Search(string name , int page = 1)
        //{
        //    page = page < 1 ? 1 : page;
        //    int pageSize = 7;
        //    var books = _context.Search(name);
        //    ViewData["SearchName"] = name;
        //    return View(books);
        //}

        [AuthenAdmin]
        public ActionResult IndexAdmin(string name, int page = 1)
        {
            page = page < 1 ? 1 : page;
            int pageSize = 7;


            IPagedList<Book> books = _context.GetPagedBooks(name, page, pageSize);
            if (!string.IsNullOrEmpty(name) && (books == null || !books.Any()))
            {
                ViewBag.Message = "Không tồn tại sách nào theo kết quả tìm kiếm.";
            }
            ViewData["SearchName"] = name;
            return View(books);
        }

        [AuthenAdmin]
        public ActionResult Edit(int id)
        {
            var bookDto = _context.GetById(id);
            if (bookDto == null)
            {
                return NotFound();
            }
            ViewBag.Authors = new SelectList(_data.authors.ToList(), "IdAuthor", "NameAuthor");
            ViewBag.Genres = new SelectList(_data.genres.ToList(), "IdGenres", "NameGenres");
            return View(bookDto);
        }

        [AuthenAdmin]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UpdateBookDto book)
        {
            if (ModelState.IsValid)
            {
                _context.Update(book);
                return RedirectToAction("IndexAdmin"); 
            }
            ViewBag.Authors = new SelectList(_data.authors.ToList(), "IdAuthor", "NameAuthor");
            ViewBag.Genres = new SelectList(_data.genres.ToList(), "IdGenres", "NameGenres");
            return View(book); 
        }

        [AuthenAdmin]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var book = _context.GetById(id); 
            if (book == null)
            {
                return NotFound();
            }

            _context.Delete(id); 
            return RedirectToAction("IndexAdmin"); 
        }

        [AuthenAdmin]
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Author = new SelectList(_data.authors.Where(b => b.deleteflag == false), "IdAuthor", "NameAuthor");
            ViewBag.Genres = new SelectList(_data.genres.Where(b => b.deleteflag == false), "IdGenres", "NameGenres");
            return View();

        }

        // POST: Books/Create
        [Authorize(Roles = "Admin")]
        [AuthenAdmin]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create([Bind("Title", "IdAuthor" , "IdGenres", "SubTitle", "Image", "Description", "PublishingYear", "QuantityInStock", "IdGenres")]CreateBookDto model)
        {
            if (ModelState.IsValid)
                    {
                        _context.Create(model);
                        return RedirectToAction("IndexAdmin");
                    }


            ViewBag.Author = new SelectList(_data.authors.Where(b => b.deleteflag == false), "IdAuthor", "NameAuthor");
            return View();
            
        }

        [Authentication]
        public IActionResult Detail(int id)
        {
            var book = _data.books
            .Include(b => b.Author)
            .Include(b => b.Genre)
             .Include(b => b.Rating)  
                .ThenInclude(r => r.User) 
            .FirstOrDefault(b => b.IdBook == id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }
    }
}

Controllers/GenresController.cs
using ThuvienMvc.Dtos.AuthorDto;
using ThuvienMvc.Dtos.GenreDto;
using ThuvienMvc.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Azure;
using ThuvienMvc.Models;
using X.PagedList;
using ThuvienMvc.Models.Authentications;

namespace ThuvienMvc.Controllers
{
    public class GenresController : Controller
    {
        private readonly IGenreservice _context;
        public GenresController(IGenreservice context)
        {
            _context = context;
        }

        [AuthenAdmin]
        public IActionResult Index(string name, int page = 1)
        {
            page = page < 1 ? 1 : page;
            int pageSize = 7;


            IPagedList<Genre> genres = _context.GetPagedGenres(name, page, pageSize);
            if (!string.IsNullOrEmpty(name) && (genres == null || !genres.Any()))
            {
                ViewBag.Message = "Không tồn tại thể loại nào theo kết quả tìm kiếm.<a href='javascript:history.back()'>Quay lại</a>";
            }
            ViewData["SearchName"] = name;
            return View(genres);
        }

        [AuthenAdmin]
        public ActionResult Create()
        {
            var model = new CreateGenre();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateGenre model)
        {
            if (ModelState.IsValid)
            {

                _context.Create(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }


        [AuthenAdmin]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var author = _context.GetById(id);
            if (author == null)
            {
                return NotFound();
            }

            _context.Delete(id);
            return RedirectToAction("Index");
        }

        [AuthenAdmin]
        public ActionResult Edit(int id)
        {
            var result = _context.GetById(id);
            if (result == null)
            {
                return NotFound();
            }

            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GenreDto genre)
        {
            if (ModelState.IsValid)
            {
                _context.Update(genre);
                return RedirectToAction("Index");
            }
            return View(genre);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ThuvienMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ThuvienMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Trang Chủ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Sách</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Borrowing" asp-action="Index">Mượn Sách</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (Context.Session.GetString("UserRole") != null)
                        {
                            <li class="nav-item">
                                <span class="navbar-text"> <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Xin chào, @Context.Session.GetString("UserName")!</a></span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Đăng Xuất</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignIn">Đăng Nhập</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ThuvienMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Chính Sách Riêng Tư</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ThuvienMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ThuvienMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Book" asp-action="IndexAdmin">LibraryMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="IndexAdmin">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Author</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genres" asp-action="Index">Genre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Borrowing" asp-action="IndexAdmin">Borrowing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="IndexAdmin">Users</a>
                        </li>
                        <ul class="navbar-nav">
                            @if (Context.Session.GetString("UserRole") != null)
                            {
                                <li class="nav-item">
                                    <span class="navbar-text"> <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Adminedit">Xin chào, @Context.Session.GetString("UserName")!</a></span>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Đăng Xuất</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignIn">Đăng Nhập</a>
                                </li>
                            }

                        </ul>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ThuvienMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>